function net = lstm1(num_channels, dataset_train, dataset_val)
	hidden_units = 120;
	
	layers = [
		sequenceInputLayer(num_channels)
		bilstmLayer(hidden_units)
		globalAveragePooling1dLayer
		fullyConnectedLayer(5)
		softmaxLayer];

	options = trainingOptions('adam', ...
		MaxEpochs=200, ...
		InitialLearnRate=0.002, ...
		GradientThreshold=1, ...
		Shuffle='every-epoch', ...
        ValidationData={dataset_val.sequences, dataset_val.labels}, ...
		Metrics='accuracy', ...
        Plots='training-progress', ...
		Verbose=false);

	net = trainnet(dataset_train.sequences, dataset_train.labels, layers, 'crossentropy', options);
end